[pytest]
addopts = -v
testpaths = 
    .
python_files = test_*.py

markers =
    counting: tests for counting_valleys
    jumping: tests for jumping_on_clouds
    string: tests for repeated_string
    socks: tests for sock_merchant
